<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
		<PackageReference Include="SoundFlow" Version="1.4.1" />
		<PackageReference Include="System.Windows.Extensions" Version="10.0.10" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Unmute.Core\Unmute.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="voices.txt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
